t3: 1.0
#####################################
# カスタム機能定義
#####################################
info:
  name: ssh
  customPackage: com.epion_t3.ssh
  summary:
    - lang: ja_JP
      contents: "SSH関連のコマンドを提供します。"
  description:
    - lang: ja_JP
      contents: "SSH関連のコマンドを提供します。"
#####################################
# コマンド定義
#####################################
commands:
  ##########################
  # ScpGet
  ##########################
  - id: ScpGet
    evidenceCommand: true
    summary:
      - lang: ja_JP
        contents: "SCPにてファイルをリモートからローカルに取得します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: SCPで「${sshConnectConfigRef}」に対して接続し「${remoteFile}」を取得します。
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "SCPを利用してリモートのファイルをローカルに取得します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "取得したファイルはエビデンスとして扱われます。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「ScpGet」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: sshConnectConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "SSH接続対象"
      - order: 6
        name: remoteFile
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "対象のリモートファイル（絶対パス）"
  ##########################
  # ScpPut
  ##########################
  - id: ScpPut
    summary:
      - lang: ja_JP
        contents: "SCPにてファイルをローカルからリモートに転送します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: SCPで「${sshConnectConfigRef}」に対して接続し「${localFile}」を「${remoteDir}」へ転送します。
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "SCPを利用してローカルのファイルをリモートへ転送します。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「ScpPut」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: sshConnectConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "SSH接続対象"
      - order: 6
        name: localFile
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "転送対象のローカルファイル"
      - order: 7
        name: remoteDir
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "転送先のリモートディレクトリ"
      - order: 8
        name: remoteFileName
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "転送先のリモートファイル名"
      - order: 9
        name: mode
        required: false
        type: string
        pattern: "[0-7]{4}"
        summary:
          - lang: ja_JP
            contents: "転送先のリモートファイルのパーミッション"
        description:
          - lang: ja_JP
            contents: "パーミッションは未指定の場合、「0600」となります。4桁で指定してください。"
  ##########################
  # ScpPutEvidence
  ##########################
  - id: ScpPutEvidence
    summary:
      - lang: ja_JP
        contents: "SCPにてファイルをローカルからリモートに転送します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: SCPで「${sshConnectConfigRef}」に対して接続し「${localFile}」を「${remoteDir}」へ転送します。
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "SCPを利用してローカルのファイルをリモートへ転送します。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「ScpPut」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: sshConnectConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "SSH接続対象"
      - order: 6
        name: target
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "転送したいエビデンスを取得したFlowIDを指定"
      - order: 7
        name: remoteDir
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "転送先のリモートディレクトリ"
      - order: 8
        name: remoteFileName
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "転送先のリモートファイル名"
      - order: 9
        name: mode
        required: false
        type: string
        pattern: "[0-7]{4}"
        summary:
          - lang: ja_JP
            contents: "転送先のリモートファイルのパーミッション"
        description:
          - lang: ja_JP
            contents: "パーミッションは未指定の場合、「0600」となります。4桁で指定してください。"
#####################################
# メッセージ定義
#####################################
messages:
  - id: com.epion_t3.ssh.err.0001
    message:
      - lang: ja_JP
        contents: SCPによるファイルのPUTに失敗しました.
  - id: com.epion_t3.ssh.err.0002
    message:
      - lang: ja_JP
        contents: SCPによるファイルのGETに失敗しました.
  - id: com.epion_t3.ssh.err.0003
    message:
      - lang: ja_JP
        contents: SSHによる接続に失敗しました。SSH接続識別子：{0}
  - id: com.epion_t3.ssh.err.0004
    message:
      - lang: ja_JP
        contents: 公開鍵が存在しません。パス：{0}
